name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Set up Ko
        uses: ko-build/setup-ko@v0.9

      - name: Test
        run: go test -v ./...

      - name: Build
        run: ko build -v ./cmd/broadcaster
